apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server.fullname" . }}
data:
  settings.json: |
    {
      {{- range $key, $value := .Values.appSettings}}
      {{ $key | quote }}:{{ $value | quote}},
      {{- end }}
    }